{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.136.1202.0 (24.09)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Procurement\",\"Inventory\",\"Warehouse\",\"_Measure\",\"StartDate\",\"EndDate\",\"Date\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\",\"DaxQueryView_Desktop\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "StartDate",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ],
        "expression": "#date(2023, 12, 1) meta [IsParameterQuery=true, Type=\"Date\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "f18a5ee5-7971-4368-bff5-28091c9ee7a4"
      },
      {
        "name": "EndDate",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ],
        "expression": "#date(2024, 2, 29) meta [IsParameterQuery=true, Type=\"Date\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "4c1072a2-0cf9-4cc9-a11e-48356e2ab841"
      }
    ],
    "relationships": [
      {
        "name": "b4bf03c1-7bbb-f869-1dbb-237ef982e593",
        "fromColumn": "Delivery Date",
        "fromTable": "Procurement",
        "toColumn": "Dates",
        "toTable": "Date"
      },
      {
        "name": "79577448-a92b-3d27-e8be-5131d4416fbe",
        "fromColumn": "Purchase Requisition Date",
        "fromTable": "Procurement",
        "isActive": false,
        "toColumn": "Dates",
        "toTable": "Date"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Procurement",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Supplier ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b8d3953-4855-4165-aa31-15d99cf2b649",
            "sourceColumn": "Supplier ID",
            "summarizeBy": "none"
          },
          {
            "name": "Cost Savings ($)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8bdc1f15-2281-4c3f-977a-1b6fa0fe9022",
            "sourceColumn": "Cost Savings ($)",
            "summarizeBy": "sum"
          },
          {
            "name": "Baseline Cost ($)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "da96f1a4-30f9-43d7-8ae3-f056ccd873be",
            "sourceColumn": "Baseline Cost ($)",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual Cost ($)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2889c7f8-77de-479c-acb1-b3adc380f7fe",
            "sourceColumn": "Actual Cost ($)",
            "summarizeBy": "sum"
          },
          {
            "name": "Sum of Lead Times (days)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "00e2e409-fa1e-4983-8fbd-c62dce491cc4",
            "sourceColumn": "Sum of Lead Times (days)",
            "summarizeBy": "sum"
          },
          {
            "name": "Number of Orders",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0bcf4e1b-7524-4f50-9345-5b7886dbf1c9",
            "sourceColumn": "Number of Orders",
            "summarizeBy": "sum"
          },
          {
            "name": "Number of On-Time Deliveries",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9da9558e-3001-4c30-be9e-34d7adfec270",
            "sourceColumn": "Number of On-Time Deliveries",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Deliveries",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "e881af46-ee22-4f8a-aba3-eeae6ad87c00",
            "sourceColumn": "Total Deliveries",
            "summarizeBy": "sum"
          },
          {
            "name": "Delivery Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "84faf333-2da5-4d28-a514-48bf6e97249a",
            "sourceColumn": "Delivery Date",
            "summarizeBy": "none"
          },
          {
            "name": "Purchase Requisition Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yyyy",
            "lineageTag": "dbf287db-467d-473f-8160-0eacab6b67bb",
            "sourceColumn": "Purchase Requisition Date",
            "summarizeBy": "none"
          },
          {
            "name": "Number of Accurate Orders",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "55ded573-7740-4af2-b98b-b6a167f813ae",
            "sourceColumn": "Number of Accurate Orders",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Purchase Orders",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4bcf9fc1-5295-479a-bb36-e0bfcdd2b218",
            "sourceColumn": "Total Purchase Orders",
            "summarizeBy": "sum"
          },
          {
            "name": "Number of Defective Items",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e8ffc42f-a2bf-4ba4-8075-27964ecf6a53",
            "sourceColumn": "Number of Defective Items",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Items Received",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "737f2b15-41c0-4ce3-8c9c-5e5126d4fd56",
            "sourceColumn": "Total Items Received",
            "summarizeBy": "sum"
          },
          {
            "name": "Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74558e68-a41e-459e-96ad-873d8b7d9147",
            "sourceColumn": "Group",
            "summarizeBy": "none"
          },
          {
            "name": "Start_of_month _Delivery",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": "STARTOFMONTH(Procurement[Delivery Date])",
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "lineageTag": "ce977256-bc97-4237-9861-a15b15bf0f0c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Pur_Start_of_month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": "STARTOFMONTH(Procurement[Purchase Requisition Date])",
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "lineageTag": "52b23305-871f-4946-a5e2-5f7710041e54",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "af5b6d35-2630-4e17-ab6e-bd8ad25ad08d",
        "measures": [
          {
            "name": "Average Lead Time (days)",
            "expression": "AVERAGE(Procurement[Sum of Lead Times (days)])",
            "formatString": "0",
            "lineageTag": "464b5431-af3c-4212-a837-15d196dbcf1e"
          },
          {
            "name": "Total Orders",
            "expression": [
              "SUM('Procurement'[Number of Accurate Orders]) + SUM('Procurement'[Number of Defective Items])",
              ""
            ],
            "formatString": "0",
            "lineageTag": "45ba4825-5f23-4833-b7db-654d5b190680"
          },
          {
            "name": "Supplier Rank",
            "expression": [
              "RANKX(",
              "    ALL('Procurement'[Supplier ID]),",
              "    [Total Orders],",
              "    ,",
              "    DESC,",
              "    DENSE",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "2ac81e34-28ed-432b-a20f-7d9943906a8c"
          },
          {
            "name": "Top 10 Suppliers",
            "expression": "IF([Supplier Rank] <= 10, 1, 0)",
            "formatString": "0",
            "lineageTag": "3c205e20-440e-4cb6-bc6f-03795d6632e0"
          },
          {
            "name": "Total Items_Received",
            "expression": "SUM('Procurement'[Total Items Received])",
            "formatString": "0",
            "lineageTag": "a5cec255-82f2-4a05-9b36-10238df3179d"
          },
          {
            "name": "Last Month Orders",
            "expression": [
              "",
              "    CALCULATE(",
              "        COUNTROWS(Procurement),",
              "        FILTER(",
              "            Procurement,",
              "            MONTH(Procurement[Purchase Requisition Date]) = MONTH(LASTDATE(Procurement[Purchase Requisition Date])) &&",
              "            YEAR(Procurement[Purchase Requisition Date]) = YEAR(TODAY())",
              "        )",
              "    )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "b5ac521d-ebcd-42ae-a5a1-dd191b86d059"
          },
          {
            "name": "On-Time Delivery Rate",
            "expression": [
              "",
              "    DIVIDE(",
              "        SUM('Procurement'[Number of On-Time Deliveries]), ",
              "        SUM('Procurement'[Total Deliveries])",
              "    ) "
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "782a62ba-500f-4943-b8f9-f4d8fc74a919"
          }
        ],
        "partitions": [
          {
            "name": "Procurement",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=1croRjS3D4K204xIdRBcd0T9TSFBBkvzL\"),[Delimiter=\",\", Columns=14, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Supplier ID\", type text}, {\"Cost Savings ($)\", Int64.Type}, {\"Baseline Cost ($)\", Int64.Type}, {\"Actual Cost ($)\", Int64.Type}, {\"Sum of Lead Times (days)\", Int64.Type}, {\"Number of Orders\", Int64.Type}, {\"Number of On-Time Deliveries\", Int64.Type}, {\"Total Deliveries\", Int64.Type}, {\"Delivery Date\", type text}, {\"Purchase Requisition Date\", type text}, {\"Number of Accurate Orders\", Int64.Type}, {\"Total Purchase Orders\", Int64.Type}, {\"Number of Defective Items\", Int64.Type}, {\"Total Items Received\", Int64.Type}}),",
                "    #\"Changed Type with Locale\" = Table.TransformColumnTypes(#\"Changed Type\", {{\"Delivery Date\", type date}}, \"en-GB\"),",
                "    #\"Changed Type with Locale1\" = Table.TransformColumnTypes(#\"Changed Type with Locale\", {{\"Purchase Requisition Date\", type date}}, \"en-GB\"),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type with Locale1\", \"Custom\", each if [Number of Defective Items] < 30 then \"Group_A\" else if [Number of Defective Items] < 60 then \"Group_B\" else if [Number of Defective Items] < 90 then \"Group_C\" else \"Group_D\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Conditional Column\",{{\"Custom\", \"Group\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Inventory",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Product ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44376d93-7a61-4569-a49f-fc56139d9941",
            "sourceColumn": "Product ID",
            "summarizeBy": "none"
          },
          {
            "name": "Average Inventory ($)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "78e3823f-6829-42ef-bc74-a46bcb18ab21",
            "sourceColumn": "Average Inventory ($)",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost of Goods Sold (COGS) ($)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e1167101-71f3-49f2-9e35-1c9afbfa996f",
            "sourceColumn": "Cost of Goods Sold (COGS) ($)",
            "summarizeBy": "sum"
          },
          {
            "name": "Number of Stockouts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d6cc8eeb-799a-427b-a011-bd8d4a117d0b",
            "sourceColumn": "Number of Stockouts",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Order Occasions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "e37af7eb-2c36-4654-b4dd-15fa6c21e931",
            "sourceColumn": "Total Order Occasions",
            "summarizeBy": "sum"
          },
          {
            "name": "Carrying Cost Percentage (%)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "377e84a0-a35c-40c7-80ae-cef15cc2e393",
            "sourceColumn": "Carrying Cost Percentage (%)",
            "summarizeBy": "sum"
          },
          {
            "name": "Number of Returned Items",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "e4d5194d-a1ce-4189-ad95-87ed56fb3e43",
            "sourceColumn": "Number of Returned Items",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Items Sold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "dataType": "int64",
<<<<<<< Updated upstream
            "formatString": "0.0",
=======
            "formatString": "#,0",
>>>>>>> Stashed changes
            "lineageTag": "f142f437-02ce-4b71-93e8-4f7a076030d0",
            "sourceColumn": "Total Items Sold",
            "summarizeBy": "sum"
          },
          {
            "name": "Accurate Inventory Counts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "297047e2-b33e-4543-ae34-89b174fbc3f2",
            "sourceColumn": "Accurate Inventory Counts",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Inventory Counts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "dataType": "int64",
<<<<<<< Updated upstream
            "formatString": "0.0",
=======
            "formatString": "#,0",
>>>>>>> Stashed changes
            "lineageTag": "bbc49c57-489b-45ac-9d99-667b2e56fdc9",
            "sourceColumn": "Total Inventory Counts",
            "summarizeBy": "sum"
          },
          {
            "name": "Lead Time Demand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6ea06d5d-c73c-4977-bdc0-421880b26d64",
            "sourceColumn": "Lead Time Demand",
            "summarizeBy": "sum"
          },
          {
            "name": "Safety Stock",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "016e1f49-f161-441c-aeeb-3f74f9ddf333",
            "sourceColumn": "Safety Stock",
            "summarizeBy": "sum"
          },
          {
            "name": "Correct Cycle Counts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "861c770c-37d7-4bc3-93e3-ba793e3c7f1d",
            "sourceColumn": "Correct Cycle Counts",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Cycle Counts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "727c49b5-8d99-4902-a055-9e1a39e8b5d1",
            "sourceColumn": "Total Cycle Counts",
            "summarizeBy": "sum"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    Inventory[Number of Stockouts] = 0, \"No Stock\",",
              "    Inventory[Number of Stockouts] > 0 && Inventory[Number of Stockouts] <= 5, \"Low Stock\",",
              "    Inventory[Number of Stockouts] > 5 && Inventory[Number of Stockouts] <= 10, \"Moderate Stock\",",
              "    Inventory[Number of Stockouts] > 10, \"High Stock\",",
              "    \"Unknown\"",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "31e79413-dc82-4694-99a1-ad19fc8bc850",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Return Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    Inventory[Number of Returned Items] = 0, \"No Returns\",",
              "    Inventory[Number of Returned Items] > 0 && Inventory[Number of Returned Items] <= 10, \"Low Returns\",",
              "    Inventory[Number of Returned Items] > 10 && Inventory[Number of Returned Items] <= 30, \"Moderate Returns\",",
              "    Inventory[Number of Returned Items] > 30, \"High Returns\",",
              "    \"Unknown\"",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "71dbe5b7-f429-4bee-b984-7b6441e47f8e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Return Segment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    Inventory[Number of Returned Items] = 0, \"No Returns\",",
              "    Inventory[Number of Returned Items] > 0 && Inventory[Number of Returned Items] <= 10, \"Low Returns\",",
              "    Inventory[Number of Returned Items] > 10 && Inventory[Number of Returned Items] <= 30, \"Moderate Returns\",",
              "    Inventory[Number of Returned Items] > 30, \"High Returns\",",
              "    \"Unknown\"",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "670748ef-2f2e-4328-a514-d3c1d9ca0688",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Sales Vol",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    Inventory[Total Items Sold] <= 7000, \"Small\",",
              "    Inventory[Total Items Sold] > 7000 && Inventory[Total Items Sold] <= 15000, \"Medium\",",
              "    Inventory[Total Items Sold] > 15000, \"Big\",",
              "    \"Unknown\"",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "44102c9c-8543-4db6-9988-f3e95a075620",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
<<<<<<< Updated upstream
            "name": "DemandCategory",
=======
            "name": "Delivery Status",
>>>>>>> Stashed changes
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(TRUE(),",
<<<<<<< Updated upstream
              "   [Lead Time Demand] <= 20, \"Low\",",
              "   [Lead Time Demand] <= 80, \"Medium\",",
              "   [Lead Time Demand] > 80, \"High\"",
=======
              "   [Lead Time Demand] <= 30, \"Urgent\",",
              "   [Lead Time Demand] >=31 && Inventory[Lead Time Demand]<= 60, \"Moderate\",",
              "   [Lead Time Demand] >=51, \"General\"",
>>>>>>> Stashed changes
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "ce6ca400-69f4-4c32-97bc-16913e991581",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Lead time Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
<<<<<<< Updated upstream
              "    Inventory[Lead Time Demand] <= 40 , \"Low Lead Time\",",
              "    Inventory[Lead Time Demand] > 40 && Inventory[Lead Time Demand] <= 80, \"Moderate Lead Time\",",
              "    Inventory[Lead Time Demand] > 80 && Inventory[Number of Stockouts] <= 120, \"High Lead Time\",",
              "    Inventory[Lead Time Demand] > 120, \"Very High Lead Time\",",
=======
              "    Inventory[Lead Time Demand] <= 20 , \"Low\",",
              "    Inventory[Lead Time Demand] > 20 && Inventory[Lead Time Demand] <= 60, \"Moderate\",",
              "    Inventory[Lead Time Demand] > 60 && Inventory[Number of Stockouts] <= 120, \"High\",",
              "    Inventory[Lead Time Demand] > 120, \"Very High\",",
>>>>>>> Stashed changes
              "    \"Unknown\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "5088280a-e2f6-47ca-a1c0-c8861a0a4690",
            "summarizeBy": "none",
            "type": "calculated"
<<<<<<< Updated upstream
=======
          },
          {
            "name": "Avg. Daily Demand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "26a9fbb1-09f6-4452-af39-c15a6271041f",
            "sourceColumn": "Avg. Daily Demand",
            "summarizeBy": "sum"
>>>>>>> Stashed changes
          }
        ],
        "lineageTag": "2e59b092-8803-4b85-b33a-d2455cf9648a",
        "partitions": [
          {
            "name": "Inventory",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=1tTpa02otJ9JIk-s4C9QEFDE9IwBbmpUN\"),[Delimiter=\",\", Columns=14, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Product ID\", type text}, {\"Average Inventory ($)\", Int64.Type}, {\"Cost of Goods Sold (COGS) ($)\", Int64.Type}, {\"Number of Stockouts\", Int64.Type}, {\"Total Order Occasions\", Int64.Type}, {\"Carrying Cost Percentage (%)\", type number}, {\"Number of Returned Items\", Int64.Type}, {\"Total Items Sold\", Int64.Type}, {\"Accurate Inventory Counts\", Int64.Type}, {\"Total Inventory Counts\", Int64.Type}, {\"Lead Time Demand\", Int64.Type}, {\"Safety Stock\", Int64.Type}, {\"Correct Cycle Counts\", Int64.Type}, {\"Total Cycle Counts\", Int64.Type}}),",
                "    #\"Inserted Division\" = Table.AddColumn(#\"Changed Type\", \"Division\", each [Total Order Occasions] / 30, type number),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Inserted Division\",{{\"Division\", \"Avg. Daily Demand\"}}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Renamed Columns\",{\"Product ID\", \"Average Inventory ($)\", \"Cost of Goods Sold (COGS) ($)\", \"Number of Stockouts\", \"Total Order Occasions\", \"Avg. Daily Demand\", \"Carrying Cost Percentage (%)\", \"Number of Returned Items\", \"Total Items Sold\", \"Accurate Inventory Counts\", \"Total Inventory Counts\", \"Lead Time Demand\", \"Safety Stock\", \"Correct Cycle Counts\", \"Total Cycle Counts\"})",
                "in",
                "    #\"Reordered Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Warehouse",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "WareHouse ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1fda6b32-e5c2-4021-a83e-44b099a4e1ea",
            "sourceColumn": "WareHouse ID",
            "summarizeBy": "none"
          },
          {
            "name": "COGS ($)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "24aa14eb-941f-4703-85d5-20535c63f103",
            "sourceColumn": "COGS ($)",
            "summarizeBy": "sum"
          },
          {
            "name": "Beginning Inventory ($)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7315dd2c-e2d2-468b-a281-2c83a00e98b5",
            "sourceColumn": "Beginning Inventory ($)",
            "summarizeBy": "sum"
          },
          {
            "name": "Ending Inventory ($)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3fd25bf1-3a52-48a6-bf27-613ffc39d252",
            "sourceColumn": "Ending Inventory ($)",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Correct Orders",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "25ce7aa5-81f5-4dab-8079-d7f0c1c4ca96",
            "sourceColumn": "Total Correct Orders",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Orders",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "58773edf-7af9-4678-98c6-1e4f701a13f8",
            "sourceColumn": "Total Orders",
            "summarizeBy": "sum"
          },
          {
            "name": "Used Storage Space (sq ft)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2e86d1eb-b4d2-41ea-8043-1e9f33de1461",
            "sourceColumn": "Used Storage Space (sq ft)",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Storage Space (sq ft)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7a259d5b-a13f-4c73-8263-87bb2843a3d7",
            "sourceColumn": "Total Storage Space (sq ft)",
            "summarizeBy": "sum"
          },
          {
            "name": "Daily Storage Utilization (%)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "22e80da9-eb2c-4083-827d-fb5718467d40",
            "sourceColumn": "Daily Storage Utilization (%)",
            "summarizeBy": "sum"
          },
          {
            "name": "Number of Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "49e5c142-e2a6-418f-9e03-993915dc9a50",
            "sourceColumn": "Number of Days",
            "summarizeBy": "sum"
          },
          {
            "name": "Number of Correct Picks",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "59d23e35-e5af-47c4-af6b-97e0f4ee88a1",
            "sourceColumn": "Number of Correct Picks",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Number of Picks",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "44ec8dd5-53f3-478e-a668-5abeab417d6f",
            "sourceColumn": "Total Number of Picks",
            "summarizeBy": "sum"
          },
          {
            "name": "Number of Backordered Items",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5dbaa96e-74dc-4b86-ae1a-9eeefc73c4d2",
            "sourceColumn": "Number of Backordered Items",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Number of Ordered Items",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b55aa2dc-d3c2-476e-8bd6-303e35e2b59e",
            "sourceColumn": "Total Number of Ordered Items",
            "summarizeBy": "sum"
          },
          {
            "name": "Warehouse Catagory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75ed2722-c48d-47d7-b884-b52e9c002f48",
            "sourceColumn": "Warehouse Catagory",
            "summarizeBy": "none"
          },
          {
            "name": "Storage_Quality",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e256466d-55ce-4493-a3f9-7c3a26b85456",
            "sourceColumn": "Storage_Quality",
            "summarizeBy": "none"
<<<<<<< Updated upstream
=======
          },
          {
            "name": "Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF(Warehouse[Used Storage Space (sq ft)] >= 2800, \"South\", IF(Warehouse[Used Storage Space (sq ft)]>=1550, \"North\", \"West\"))",
            "isDataTypeInferred": true,
            "lineageTag": "b8598295-d5d1-47f5-89d3-d737309f1f77",
            "summarizeBy": "none",
            "type": "calculated"
>>>>>>> Stashed changes
          }
        ],
        "lineageTag": "ec8fd5b5-0270-4e7a-8c38-b2a79bb293e4",
        "partitions": [
          {
            "name": "Warehouse",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=1sUI4zPXGbWhkV7lIXJRJkt4H8R6ZqNWw\"),[Delimiter=\",\", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"WareHouse ID\", type text}, {\"COGS ($)\", Int64.Type}, {\"Beginning Inventory ($)\", Int64.Type}, {\"Ending Inventory ($)\", Int64.Type}, {\"Total Correct Orders\", Int64.Type}, {\"Total Orders\", Int64.Type}, {\"Used Storage Space (sq ft)\", Int64.Type}, {\"Total Storage Space (sq ft)\", Int64.Type}, {\"Daily Storage Utilization (%)\", type number}, {\"Number of Days\", Int64.Type}, {\"Number of Correct Picks\", Int64.Type}, {\"Total Number of Picks\", Int64.Type}, {\"Number of Backordered Items\", Int64.Type}, {\"Total Number of Ordered Items\", Int64.Type}, {\"\", type text}, {\"_1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"\", \"_1\"}),",
                "    #\"Catagory Define\" = Table.AddColumn(#\"Removed Columns\", \"Warehouse Catagory\", each if [#\"Total Storage Space (sq ft)\"] < 1200 then \"Small\" else if [#\"Total Storage Space (sq ft)\"] < 3000 then \"Medium\" else if [#\"Total Storage Space (sq ft)\"] < 4500 then \"Large\" else \"Big\"),",
                "    #\"Storage Quality Define\" = Table.AddColumn(#\"Catagory Define\", \"Storage_Quality\", each if [#\"Daily Storage Utilization (%)\"] >= 90 then \"Overloaded\" else if [#\"Daily Storage Utilization (%)\"] >= 70 then \"Efficient\" else if [#\"Daily Storage Utilization (%)\"] >= 50 then \"Balanced\" else \"Underutilized\")",
                "in",
                "    #\"Storage Quality Define\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Measure",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "fd8ab426-1ba4-4188-b188-2bbff5ce4d6c",
        "measures": [
          {
            "name": "Actual Cost",
            "displayFolder": "Procurement",
            "expression": "SUM(Procurement[Actual Cost ($)])",
            "formatString": "0",
            "lineageTag": "75a61099-3cac-4380-adbf-667b18e46e2b"
          },
          {
            "name": "Total_correct_orders",
            "displayFolder": "Wirehouse",
            "expression": "SUM(Warehouse[Total Correct Orders])",
            "formatString": "0",
            "lineageTag": "7951ada3-749c-479c-b276-528aa449c8f6"
          },
          {
            "name": "COGS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Inventory",
            "expression": "SUM(Inventory[Cost of Goods Sold (COGS) ($)])",
<<<<<<< Updated upstream
            "formatString": "0.0",
=======
            "formatString": "#,0",
>>>>>>> Stashed changes
            "lineageTag": "e6fa9544-a2c1-420c-953f-b5c153f2fbf9"
          },
          {
            "name": "DOH",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Inventory",
            "expression": [
              "",
              "DIVIDE(",
              "    SUM(Inventory[Average Inventory ($)]),",
              "    SUM(Inventory[Cost of Goods Sold (COGS) ($)])",
              ") * 365"
            ],
            "formatString": "0",
            "lineageTag": "1d39473f-00e0-4d5e-b4f4-b3c810cfccd9"
          },
          {
            "name": "Stockout Rate",
            "displayFolder": "Inventory",
            "expression": [
              "",
              "    DIVIDE(",
              "        SUM(Inventory[Number of Stockouts]),",
              "        SUM(Inventory[Total Order Occasions])",
              "    )",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "e1858fb7-706e-4786-9efb-a8765c510cab"
          },
          {
            "name": "Carrying Cost",
<<<<<<< Updated upstream
            "displayFolder": "Inventory",
            "expression": "SUMX('Inventory', 'Inventory'[Average Inventory ($)] * 'Inventory'[Carrying Cost Percentage (%)] / 100)",
            "formatString": "0.0",
=======
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Inventory",
            "expression": "SUMX('Inventory', 'Inventory'[Average Inventory ($)] * 'Inventory'[Carrying Cost Percentage (%)] / 100)",
            "formatString": "0",
>>>>>>> Stashed changes
            "lineageTag": "5a5da6e8-b145-4457-9745-2c158e6f9704"
          },
          {
            "name": "Rate of Return",
            "displayFolder": "Inventory",
            "expression": [
              "",
              "DIVIDE(",
              "    SUM(Inventory[Number of Returned Items]),",
              "    SUM(Inventory[Total Items Sold])",
              ") * 100"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "be7fab34-f7fd-4a10-85bb-1c2628cdf79e"
          },
          {
            "name": "Inventory Accuracy",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Inventory",
            "expression": [
              "",
              "DIVIDE(",
              "    SUM(Inventory[Accurate Inventory Counts]),",
              "    SUM(Inventory[Total Inventory Counts])",
              ") * 100",
              ""
            ],
            "lineageTag": "3272335e-2a14-4c1e-bbf6-2b282cd2481f"
          },
          {
<<<<<<< Updated upstream
            "name": "Reorder Point",
            "displayFolder": "Inventory",
            "expression": [
              "",
              "SUM(Inventory[Lead Time Demand]) + SUM(Inventory[Safety Stock])"
            ],
            "formatString": "0",
            "lineageTag": "abdd399f-0b96-4dce-948f-1f44f21578a1"
          },
          {
            "name": "Cycle Count Accuracy (Percentage)",
=======
            "name": "Re-Order Point",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
>>>>>>> Stashed changes
            "displayFolder": "Inventory",
            "expression": [
              "",
              "(SUM(Inventory[Safety Stock]) +(average(Inventory[Avg. Daily Demand]))*AVERAGE(Inventory[Lead Time Demand]))"
            ],
            "lineageTag": "abdd399f-0b96-4dce-948f-1f44f21578a1"
          },
          {
            "name": "Cycle Count Accuracy (Percentage)",
            "displayFolder": "Inventory",
            "expression": [
              "",
              "DIVIDE(",
              "    SUM(Inventory[Correct Cycle Counts]),",
              "    SUM(Inventory[Total Cycle Counts])",
              ")",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "2618d294-b70a-4dcf-90a6-3c9130b61735"
          },
          {
            "name": "Cost Savings",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Procurement",
            "expression": "SUM(Procurement[Cost Savings ($)])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "bdd438cf-4b04-4370-ba41-9ecbda7f3faf"
          },
          {
            "name": "Total Order",
            "displayFolder": "Procurement",
            "expression": "SUM(Procurement[Number of Orders])",
            "formatString": "0.0",
            "lineageTag": "b30440a1-f436-4c58-a82d-ec74cda3a4ee"
          },
          {
            "name": "Defective_Items",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Procurement",
            "expression": "SUM(Procurement[Number of Defective Items])",
            "lineageTag": "3009c894-302e-4c23-bbd6-46763b8699e7"
          },
          {
            "name": "Total Deliveries",
            "displayFolder": "Procurement",
            "expression": "SUM(Procurement[Total Deliveries])",
            "formatString": "#,0.0",
            "lineageTag": "1284068e-00f2-49d2-8f79-72f6697e4608"
          },
          {
            "name": "On time Deliveries",
            "displayFolder": "Procurement",
            "expression": "SUM(Procurement[Number of On-Time Deliveries])",
            "formatString": "0",
            "lineageTag": "f0a48b97-e18b-47df-bf5a-7e76046c2852"
          },
          {
            "name": "Number of Order",
            "displayFolder": "Procurement",
            "expression": "SUM(Procurement[Number of Orders])",
            "formatString": "0",
            "lineageTag": "ae1ff50c-dbcc-46b7-93aa-80dd4a4002ca"
          },
          {
            "name": "Number of Accurate Orders",
            "displayFolder": "Procurement",
            "expression": "SUM(Procurement[Number of Accurate Orders])",
            "formatString": "0",
            "lineageTag": "1aef717e-23cd-4639-b1a2-e86b67167db2"
          },
          {
            "name": "Guge Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Procurement",
            "expression": "CALCULATE([Average Lead Time (days)]*1.1, REMOVEFILTERS(Procurement[Group]))",
            "lineageTag": "1d142dfe-5982-4c8d-b470-b3f998366f58"
          },
          {
            "name": "Guge Maximum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Procurement",
            "expression": [
              "",
              "VAR avg_lead_time = [Average Lead Time (days)]",
              "VAR Guge_max_Reg = [Guge Target]*1.2",
              "VAR Guge_target = avg_lead_time*1.2",
              "VAR Result = IF(avg_lead_time>Guge_max_Reg,Guge_target, Guge_max_Reg )",
              "RETURN",
              "Result"
            ],
            "lineageTag": "81dcd5d1-1da6-4792-b321-a68597b33243"
          },
          {
            "name": "Defect Items %",
            "displayFolder": "Procurement",
            "expression": "DIVIDE([Defective_Items], [Total Item Received])",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "32d81902-e3a0-465d-9c21-f47c5d1b95c0"
          },
          {
            "name": "Acurate Order %",
            "displayFolder": "Procurement",
            "expression": [
              "",
              "VAR acurate_order = SUM(Procurement[Number of Accurate Orders])",
              "// VAR Total_purchese_order  = AVERAGE(Procurement[Total Purchase Orders])//",
              "VAR Number_of_total_order = SUM(Procurement[Number of Orders])",
              "VAR Result = DIVIDE(acurate_order, Number_of_total_order, 0)",
              "RETURN",
              "Result"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "a3b324d5-2772-4665-a732-e912ffb86dea"
          },
          {
            "name": "% Cost Saving",
            "displayFolder": "Procurement",
            "expression": [
              "",
              "VAR Cost_Saving_Average = AVERAGE(Procurement[Cost Savings ($)])",
              "VAR Actual_cost_Agerage = AVERAGE(Procurement[Actual Cost ($)])",
              "VAR Result = DIVIDE(Cost_Saving_Average, Actual_cost_Agerage, 0)",
              "RETURN",
              "Result"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "0837b6ab-eac9-4497-9b6e-01adc7fbcc05"
          },
          {
            "name": "Supplier Reliability %",
            "displayFolder": "Procurement",
            "expression": "DIVIDE([On time Deliveries], [Total Deliveries], 0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "3093dff9-0a8c-4863-9062-6da58cb633bd"
          },
          {
            "name": "Total Item Received",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Procurement",
            "expression": "SUM(Procurement[Total Items Received])",
            "formatString": "#,0",
            "lineageTag": "5f9b5f93-178c-4c98-b042-48d6f59eda7a"
          },
          {
            "name": "PY Cost Savings",
            "displayFolder": "Procurement",
            "expression": "CALCULATE([Cost Savings], PREVIOUSMONTH('Date'[Dates]))",
            "formatString": "0",
            "lineageTag": "c3ecc3fe-8d9a-4035-9923-d7653d51a75c"
          },
          {
            "name": "PM_CS",
            "displayFolder": "Procurement",
            "expression": "CALCULATE([Cost Savings], PREVIOUSMONTH('Date'[Dates]))",
            "formatString": "0",
            "lineageTag": "d6b73519-60e6-493c-a840-6a6ca17b48c9"
          },
          {
            "name": "Last Motnh Cost Saving",
            "displayFolder": "Procurement",
            "expression": "CALCULATE([Cost Savings], PREVIOUSMONTH(Procurement[Delivery Date]))",
            "formatString": "0",
            "lineageTag": "65a9aff8-3d7d-440f-a735-3fcb927e5c1d"
          },
          {
            "name": "Top Supplier by Cost Savings",
            "displayFolder": "Procurement",
            "expression": [
              "",
              "    CALCULATE(",
              "        MAX('Procurement'[Supplier ID]),",
              "        TOPN(",
              "            4, ",
              "            SUMMARIZE(",
              "                'Procurement', ",
              "                'Procurement'[Supplier ID], ",
              "                \"CostSavings\", ",
              "                SUM('Procurement'[Cost Savings ($)])",
              "            ), ",
              "            [CostSavings], ",
              "            DESC",
              "        )",
              "    )"
            ],
            "lineageTag": "59a59e55-61ea-4eea-9e1a-dd840e6d92d2"
          },
          {
            "name": "Average Cycle Time (days)",
            "displayFolder": "Procurement",
            "expression": "AVERAGEX( Procurement, DATEDIFF( Procurement[Purchase Requisition Date], Procurement[Delivery Date], DAY))",
            "formatString": "0",
            "lineageTag": "789fc128-a866-44b7-9be5-32ef26dad55e"
          },
          {
            "name": "Baseline Cost",
            "displayFolder": "Procurement",
            "expression": "SUM(Procurement[Baseline Cost ($)])",
            "formatString": "0",
            "lineageTag": "618fcbc5-fc8d-4932-9d57-0c09e01a4117"
          },
          {
            "name": "Average_Inventory",
            "displayFolder": "Wirehouse",
            "expression": [
              "DIVIDE(SUM('Warehouse'[Beginning Inventory ($)]) + SUM('Warehouse'[Ending Inventory ($)]), 2)",
              "",
              "",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "ce34bec0-6a32-4ce8-8f45-ae4b617b3164"
          },
          {
            "name": "Backorder_Rate",
            "displayFolder": "Wirehouse",
            "expression": [
              "",
              "DIVIDE(SUM(Warehouse[Number of Backordered Items]), ",
              "SUM('Warehouse'[Total Number of Ordered Items]), 0)",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "dcb2807a-d1c6-42ce-8462-0429c894b3c4"
          },
          {
            "name": "Backorder_Rate_Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Wirehouse",
            "expression": [
              "0.03 // Set this to your desired target rate",
              ""
            ],
            "lineageTag": "aec62549-a06a-42fa-85a7-ed95e8c11468"
          },
          {
            "name": "COGS_Backorder_Impact",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Wirehouse",
            "expression": [
              "[COGS_Per_Order] * SUM('Warehouse'[Number of Backordered Items])",
              ""
            ],
            "lineageTag": "c2b79238-a753-4b99-bd33-1917a2fee886"
          },
          {
            "name": "COGS_Per_Order",
            "displayFolder": "Wirehouse",
            "expression": [
              "DIVIDE(SUM('Warehouse'[COGS ($)]), SUM('Warehouse'[Total Orders]))",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "91792b73-5a42-4ceb-ba62-5d012f58d8f8"
          },
          {
            "name": "COGS_Per_Ordered_Item",
            "displayFolder": "Wirehouse",
            "expression": [
              "DIVIDE(SUM('Warehouse'[COGS ($)]), SUM('Warehouse'[Total Number of Ordered Items]))",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "dfaea90c-e186-4d89-97b8-aef9dc6747e1"
          },
          {
            "name": "Highest_Storage_Utilization",
            "displayFolder": "Wirehouse",
            "expression": [
              "MAX('Warehouse'[Daily Storage Utilization (%)])/100",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "a55459d4-7912-4bd4-930b-215aabf51b04"
          },
          {
            "name": "Stock_Turnover_Ratio",
            "displayFolder": "Wirehouse",
            "expression": [
              "",
              "DIVIDE(",
              "    SUM('Warehouse'[COGS ($)]),",
              "    AVERAGEX(",
              "        'Warehouse',",
              "        DIVIDE(",
              "            'Warehouse'[Beginning Inventory ($)] + Warehouse[Ending Inventory ($)],",
              "            2",
              "        )",
              "    )",
              ")/100",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "04f0a536-af39-4c18-816a-2f33d6b309be"
          },
          {
            "name": "Lowest_Storage_Utilization",
            "displayFolder": "Wirehouse",
            "expression": [
              "MIN(Warehouse[Daily Storage Utilization (%)])/100",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "efa8bdbe-b6c9-47ed-aa02-8ff381f1c456"
          },
          {
            "name": "Max_Backorder",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Wirehouse",
            "expression": [
              "0.05 // Set this to your desired target rate",
              ""
            ],
            "lineageTag": "0da2472e-b1ef-47c4-9019-419b7e18a51e"
          },
          {
            "name": "Min_Backorder",
            "displayFolder": "Wirehouse",
            "expression": [
              "0 // Set this to your desired target rate",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "d166065f-0a78-481f-b949-f04dc52532ad"
          },
          {
            "name": "Order_Accuracy",
            "displayFolder": "Wirehouse",
            "expression": [
              "DIVIDE(SUM('Warehouse'[Total Correct Orders]), SUM('Warehouse'[Total Orders]), 0)",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "935ac16b-ae1d-40d4-ab1c-fc56bd8ab642"
          },
          {
            "name": "Picking_Accuracy",
            "displayFolder": "Wirehouse",
            "expression": "DIVIDE(SUM(Warehouse[Number of Correct Picks]), SUM(Warehouse[Total Number of Picks]), 0) ",
            "formatString": "0%;-0%;0%",
            "lineageTag": "20412242-1ace-428a-a57c-88c4190db105"
          },
          {
            "name": "Storage_Utilization",
            "displayFolder": "Wirehouse",
            "expression": "DIVIDE(SUM(Warehouse[Used Storage Space (sq ft)]),SUM(Warehouse[Total Storage Space (sq ft)]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "7b0e99de-97cf-46eb-b831-05f71b8ca98a"
          },
          {
            "name": "Total_COGS",
            "displayFolder": "Wirehouse",
            "expression": "SUM(Warehouse[COGS ($)])",
            "formatString": "0",
            "lineageTag": "d8e4fc4e-f956-4dc6-887e-35f2a7bf9351"
          },
          {
            "name": "Total_Inventory_Movement",
            "displayFolder": "Wirehouse",
            "expression": [
              "SUM('Warehouse'[Ending Inventory ($)]) - SUM(Warehouse[Beginning Inventory ($)])",
              ""
            ],
            "formatString": "0",
            "lineageTag": "cc385c9a-c33a-48d1-8516-d914f966fc59"
          },
          {
            "name": "Total_Pick",
            "displayFolder": "Wirehouse",
            "expression": "SUM(Warehouse[Total Number of Picks])",
            "formatString": "0.0",
            "lineageTag": "826fce5e-bf98-46e7-b9ee-17781106a337"
          },
          {
            "name": "Total_Storage (SqFt)",
            "displayFolder": "Wirehouse",
            "expression": "SUM(Warehouse[Total Storage Space (sq ft)])",
            "formatString": "0",
            "lineageTag": "66ce4905-215d-4494-a966-d1e30d2a6424"
          },
          {
            "name": "Total_WareHouse",
            "displayFolder": "Wirehouse",
            "expression": "DISTINCTCOUNT(Warehouse[WareHouse ID])",
            "formatString": "0",
            "lineageTag": "968e0695-53be-431b-8b48-3b968946c12f"
          },
          {
            "name": "Totall_Order",
            "displayFolder": "Wirehouse",
            "expression": "SUM(Warehouse[Total Orders])",
            "formatString": "0",
            "lineageTag": "5aa85fb0-5ba1-46aa-a579-c60791f168cd"
          },
          {
            "name": "Warehouse_HighestStorage_Utilization",
            "displayFolder": "Wirehouse",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX('Warehouse'[WareHouse ID]),",
              "    FILTER('Warehouse', 'Warehouse'[Daily Storage Utilization (%)]= [Highest_Storage_Utilization])",
              ")",
              ""
            ],
            "lineageTag": "2c43b83b-a65f-4ce8-a113-99c2a6fb8585"
          },
          {
            "name": "Warehouse_Lowest_StorageUtilization",
            "displayFolder": "Wirehouse",
            "expression": [
              "",
              "CALCULATE(",
              "   MIN('Warehouse'[WareHouse ID]),",
              "    FILTER('Warehouse', 'Warehouse'[Daily Storage Utilization (%)]= [Lowest_Storage_Utilization]))"
            ],
            "lineageTag": "a6c6bc2b-5cab-4752-8809-fa94a3db7e39"
          },
          {
            "name": "Cost_Per_SqFt",
            "displayFolder": "Wirehouse",
            "expression": [
              "",
              "DIVIDE(",
              "    SUM('Warehouse'[COGS ($)]),",
              "    SUM('Warehouse'[Used Storage Space (sq ft)])",
              ")",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "36937f53-3c19-4888-8941-19f65b234bf7"
          },
          {
            "name": "Days_of_Inventory_on_Hand (DOH)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Wirehouse",
            "expression": [
              "",
              "DIVIDE(",
              "    SUM('Warehouse'[Ending Inventory ($)]),",
              "    SUM('Warehouse'[COGS ($)])",
              ") * 365",
              ""
            ],
            "lineageTag": "d9965a80-940c-46ae-8e92-09a1de621b66"
          },
          {
            "name": "Correct_Order_Percentage_per_Day",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Wirehouse",
            "expression": [
              "",
              "DIVIDE(",
              "    SUM('Warehouse'[Total Correct Orders]),",
              "    SUM('Warehouse'[Number of Days])",
              ")",
              ""
            ],
            "lineageTag": "5b3a43ca-6b73-40e0-ac4a-1574a82a7d08"
          },
          {
            "name": "Order_Processing_Efficiency",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Wirehouse",
            "expression": [
              "",
              "DIVIDE(",
              "    SUM('Warehouse'[Total Orders]),",
              "    SUM('Warehouse'[Number of Days])",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "279e0e53-bf08-4d68-86ca-939f35fca067"
          },
          {
            "name": "GaugeColorBackorder",
            "displayFolder": "Wirehouse",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    [Backorder_Rate] < .03, \"Green\",  // For rates less than 3",
              "    [Backorder_Rate] >= .03 && [Backorder_Rate] < .04, \"Orange\",  // For rates between 3 and ",
              "    \"Red\"  // for above 5",
              ")",
              "",
              ""
            ],
            "lineageTag": "23310d9b-6e1a-4690-8728-dbb830abfe60"
          },
          {
            "name": "OrderAccuracyColor",
            "displayFolder": "Wirehouse",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    [Order_Accuracy] < .50, \"Red\",    // For accuracy less than 50",
              "    [Order_Accuracy] >= .50 && [Order_Accuracy] < .66, \"Yellow\",  // For accuracy between 50 and 65",
              "    [Order_Accuracy] >= .66 && [Order_Accuracy] < .85, \"Light Green\",  // For accuracy between 66 and 84",
              "    [Order_Accuracy] >= .85, \"Green\",  // For accuracy 85 and above",
              "    \"Gray\"  // Default case if none of the above is met",
              ")",
              ""
            ],
            "lineageTag": "58000b60-5ab3-4ae6-85d4-b6318506f1f2"
          },
          {
            "name": "PickingAccuracyColor",
            "displayFolder": "Wirehouse",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    [Picking_Accuracy] < .50, \"Red\",    // For accuracy less than 50",
              "    [Picking_Accuracy] >= .50 && [Picking_Accuracy] < .66, \"Yellow\",  // For accuracy between 50 and 65",
              "    [Picking_Accuracy] >= .66 && [Picking_Accuracy] < .85, \"Light Green\",  // For accuracy between 66 and 84",
              "    [Picking_Accuracy] >= .85, \"Green\",  // For accuracy 85 and above",
              "    \"Gray\"  // Default case if none of the above is met",
              ")",
              ""
            ],
            "lineageTag": "b8a78fbd-52ce-4ad6-9d59-f7ddce610f9d"
<<<<<<< Updated upstream
=======
          },
          {
            "name": "% Return",
            "displayFolder": "Inventory",
            "expression": [
              "",
              "DIVIDE(",
              "    COUNTROWS(Inventory),",
              "    CALCULATE(COUNTROWS(Inventory), ALL(Inventory))",
              ")",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "9defe1d5-3330-41c6-9c25-52602c67fb27"
          },
          {
            "name": "CM",
            "displayFolder": "Procurement",
            "expression": [
              "",
              " CALCULATE([Cost Savings],",
              " YEAR('Date'[Dates])= YEAR(MAX('Date'[Dates])),",
              " MONTH('Date'[Dates]) = MONTH(MAX('Date'[Dates])))"
            ],
            "formatString": "0",
            "lineageTag": "64192939-39de-4bfe-8ffc-ddd1738a4b52"
          },
          {
            "name": "_PM",
            "displayFolder": "Procurement",
            "expression": [
              "",
              "VAR _curentMonth = MONTH(MAX('Date'[Dates]))",
              "VAR _curentYear = YEAR(MAX('Date'[Dates]))",
              "VAR _PreviousMonth = IF(_curentMonth=1, 12, _curentMonth-1)",
              "VAR _PreviousYear = IF(_curentMonth=1, _curentYear-1, _curentYear)",
              "RETURN",
              "    CALCULATE(",
              "        [Cost Savings],",
              "        MONTH('Date'[Dates]) = _PreviousMonth,",
              "        YEAR('Date'[Dates])=_PreviousYear)"
            ],
            "formatStringDefinition": {
              "expression": "\"0.#\""
            },
            "lineageTag": "a521c097-355e-4827-b6df-3dfa51c61eee"
          },
          {
            "name": "Cost Referance",
            "displayFolder": "Procurement",
            "expression": "\"CM \" & [CM] & \" | \" & \"PM \" & [_PM]",
            "lineageTag": "e2aba48f-2551-4aaf-8906-6c4e1c8320fb"
          },
          {
            "name": "Detail CS",
            "displayFolder": "Procurement",
            "expression": [
              "",
              "VAR _pct = DIVIDE([Cost Savings], [PM_CS])-1",
              "RETURN",
              "FORMAT(_pct, \"0%\") & ",
              "    IF(_pct > 0, \" \", \" \")"
            ],
            "lineageTag": "17f547e4-ea90-43d6-8042-3c389e670d5b"
          },
          {
            "name": "PM_TO",
            "displayFolder": "Procurement",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Order],",
              "    PREVIOUSMONTH('Date'[Dates])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "ed025504-2640-4445-abe7-efe9e9f0ac21"
          },
          {
            "name": "PM DI",
            "displayFolder": "Procurement",
            "expression": [
              "",
              "CALCULATE([Defect Items %],",
              "PREVIOUSMONTH('Date'[Dates])",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "4f7867ac-93ea-4d23-addf-03480069d769"
          },
          {
            "name": "Detail TO",
            "displayFolder": "Procurement",
            "expression": [
              "",
              "VAR _pct = DIVIDE([Total Order], [PM_TO])-1",
              "RETURN",
              "FORMAT(_pct, \"0%\") & ",
              "    IF(_pct > 0, \" \", \" \")"
            ],
            "lineageTag": "651c0c89-9441-47b8-9764-2a3d2e4f821f"
          },
          {
            "name": "Detail DI%",
            "displayFolder": "Procurement",
            "expression": [
              "",
              "VAR Diff = [Defect Items %] - [PM DI]",
              "VAR Symbol = IF(Diff>0, \" \", \" \")",
              "VAR Result = FORMAT(ABS(Diff), \"0.#%\") & Symbol",
              "RETURN",
              "    Result"
            ],
            "lineageTag": "0a49e43e-00f2-4275-ae1a-e4dc5240a030"
          },
          {
            "name": "PM AO",
            "displayFolder": "Procurement",
            "expression": [
              "",
              "CALCULATE(",
              "    [Acurate Order %],",
              "    PREVIOUSMONTH('Date'[Dates])",
              ")",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "881a5d30-482b-4ef0-a9c6-e100875fdcef"
          },
          {
            "name": "Detail AO%",
            "displayFolder": "Procurement",
            "expression": [
              "",
              "VAR Diff = [Acurate Order %] - [PM AO]",
              "VAR Symbol = IF(Diff>0, \" \", \" \")",
              "VAR Result = FORMAT(ABS(Diff), \"#%\") & Symbol",
              "RETURN",
              "    Result"
            ],
            "lineageTag": "6a196225-1aec-4aaf-b3c9-4d4a1ec77375"
          },
          {
            "name": "PM SR",
            "displayFolder": "Procurement",
            "expression": [
              "",
              "CALCULATE([Supplier Reliability %],",
              "PREVIOUSMONTH('Date'[Dates])",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "e5300079-71aa-4199-83dd-7ea94bfa979e"
          },
          {
            "name": "Detail SR%",
            "displayFolder": "Procurement",
            "expression": [
              "",
              "VAR Diff = [Supplier Reliability %] - [PM SR]",
              "VAR Symbol = IF(Diff>0, \" \", \" \")",
              "VAR Result = FORMAT(ABS(Diff), \"0.#%\") & Symbol",
              "RETURN",
              "    Result"
            ],
            "lineageTag": "68efc89a-34a2-4ac0-b9fc-0e05017614e7"
          },
          {
            "name": "Previous Month Cost Saving",
            "displayFolder": "Procurement",
            "expression": [
              "",
              "CALCULATE([Cost Savings], DATEADD('Date'[Dates], -1, MONTH))"
            ],
            "formatString": "0",
            "lineageTag": "91462f64-d449-41f4-ab43-005a97304e1f"
          },
          {
            "name": "Low Stock",
            "displayFolder": "Inventory",
            "expression": [
              "",
              "    var _stockCount= COUNTROWS(FILTER(Inventory, Inventory[Status]=\"Low Stock\"))",
              "",
              "    RETURN",
              "        if(ISBLANK(_stockCount),\"0\", _stockCount)"
            ],
            "formatString": "0",
            "lineageTag": "fde8793b-ee5b-4606-ba9b-2e962f7947d7"
          },
          {
            "name": "In Stock",
            "displayFolder": "Inventory",
            "expression": [
              "",
              "Var _inStock = COUNT(Inventory[Product ID])",
              "",
              "RETURN",
              "    if(ISBLANK(_inStock),\"0\", _inStock)"
            ],
            "formatString": "0",
            "lineageTag": "ec973f52-58b7-4569-af8d-20a8fc6373f1"
          },
          {
            "name": "Low Stock %",
            "displayFolder": "Inventory",
            "expression": [
              "",
              "  var _lowPercent =  DIVIDE([Low Stock],[In Stock],0)",
              "",
              "  RETURN",
              "    if(ISBLANK(_lowPercent), \"0\", _lowPercent)",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "2cf47324-e6d5-4e5f-a708-febcc16d1c29"
          },
          {
            "name": "COGS Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Inventory",
            "expression": "[COGS]*1.25",
            "lineageTag": "7fa158ac-6f74-4e20-9040-acae3fbd6c05"
>>>>>>> Stashed changes
          }
        ],
        "partitions": [
          {
            "name": "_Measure",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Date",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Dates",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isKey": true,
            "lineageTag": "9967ba5f-bb08-4db2-af16-6e48fcb9e1f3",
            "sourceColumn": "Dates",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0ce6d50f-f772-4698-99fb-dfe6f3e1cd58",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2ca4eb66-0341-4107-9362-a17ef63f2d9b",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3791c03a-68cb-45e5-96fa-8f3d527d0a62",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Week of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2e735cdb-bacd-43d4-ad23-767fca6f44bf",
            "sourceColumn": "Week of Year",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "497568ea-46b5-4c37-99e9-44d15e47cee2",
            "sortByColumn": "Month",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3eb8e294-31ab-42d2-9ab8-e3fc22e557a8",
            "sourceColumn": "Quarter Name",
            "summarizeBy": "none"
          },
          {
            "name": "Week Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cdf0864c-bde2-477c-a3c9-10d3a2bae74f",
            "sourceColumn": "Week Name",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "e48071c7-5701-4dda-9c6d-e01f6c5b0863",
            "sourceColumn": "Start of Month",
            "summarizeBy": "none"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "3398193c-9d22-4876-97e5-eac0994b1cda",
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Duration = Duration.Days(EndDate-StartDate)+1,",
                "    #\"List of date\" = List.Dates(StartDate, Duration, #duration(1,0,0,0)),",
                "    #\"Converted to Table\" = Table.FromList(#\"List of date\", Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Converted to Table\",{{\"Column1\", \"Dates\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Dates\", type date}}),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Changed Type\", \"Year\", each Date.Year([Dates]), Int64.Type),",
                "    #\"Inserted Month\" = Table.AddColumn(#\"Inserted Year\", \"Month\", each Date.Month([Dates]), Int64.Type),",
                "    #\"Inserted Quarter\" = Table.AddColumn(#\"Inserted Month\", \"Quarter\", each Date.QuarterOfYear([Dates]), Int64.Type),",
                "    #\"Inserted Week of Year\" = Table.AddColumn(#\"Inserted Quarter\", \"Week of Year\", each Date.WeekOfYear([Dates]), Int64.Type),",
                "    #\"Inserted Month Name\" = Table.AddColumn(#\"Inserted Week of Year\", \"Month Name\", each Date.MonthName([Dates]), type text),",
                "    #\"Extracted First Characters\" = Table.TransformColumns(#\"Inserted Month Name\", {{\"Month Name\", each Text.Start(_, 3), type text}}),",
                "    #\"Added Quarter Name\" = Table.AddColumn(#\"Extracted First Characters\", \"Quarter Name\", each \"Q\"& Text.From([Quarter])),",
                "    #\"Added Week Name\" = Table.AddColumn(#\"Added Quarter Name\", \"Week Name\", each \"W\"& Text.From([Week of Year])),",
                "    #\"Inserted Start of Month\" = Table.AddColumn(#\"Added Week Name\", \"Start of Month\", each Date.StartOfMonth([Dates]), type date)",
                "in",
                "    #\"Inserted Start of Month\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}